# Generated by Django 5.0.4 on 2025-01-06 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('speaker', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('hours_quantity', models.IntegerField()),
                ('articles', models.TextField(blank=True, null=True)),
                ('max_quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('local', models.TextField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('meetup', 'Meetup')], default='conference', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thematic_rooms', to='core.event')),
            ],
            options={
                'verbose_name': 'Thematic Room',
                'verbose_name_plural': 'Thematic Rooms',
                'ordering': ['id'],
            },
        ),
    ]
